######################################################################
# Automatically generated by qmake (3.0) V máj. 8 14:09:09 2016
######################################################################

TEMPLATE = app
TARGET = SamuMovie
INCLUDEPATH += .

# Input
HEADERS += GameOfLife.h SamuLife.h SamuQl.h VideoConverter.h
SOURCES += GameOfLife.cpp main.cpp SamuLife.cpp VideoConverter.cpp
